---
  - name: 'add l2 vlan'
    juniper_junos_config:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      port: "{{ port }}"
      load: 'set'
      lines:
        - 'set vlans {{ item.name }} vlan-id {{ item.id }} description {{ item.description }}'
      retrieve: 'candidate'
      #filter: 'vlans'
      ignore_warning: 'statement not found'
      comment: 'add l2 vlan {{ item.name }} via ansible'
      dest_dir: "output/"
    with_items:
      - "{{ vlans }}"
    register: response

  #- name: "Print the response"
  #  debug:
  #    var: response
